# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Douyin MCP Server
FROM python:3.11-slim

# Install ffmpeg for audio extraction
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install Python dependencies and the MCP server
RUN pip install --no-cache-dir .

# Expose no HTTP port, uses stdio
ENTRYPOINT ["douyin-mcp-server"]
